name: Merge upstream branches

on:
  schedule:
    - cron: '0 */6 * * *'  # 매 6시간마다 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기

      - name: Configure Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@khu.ac.kr"

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream https://github.com/iceprins/Algorithm-Study.git
          git fetch upstream

      - name: Merge Feature Branches
        run: |
          BRANCHES=("feature/x" "feature/y")  # 병합할 브랜치 리스트
          for BRANCH in "${BRANCHES[@]}"; do
            git checkout -b $BRANCH origin/$BRANCH || git checkout $BRANCH
            git merge --no-edit upstream/$BRANCH || true
            git push origin $BRANCH || true
          done

      - name: Merge Main Branch
        run: |
          git checkout main
          git merge --no-edit upstream/main || true
          git push origin main || true



