name: Sync Fork

on:
  workflow_dispatch: # 수동 실행 가능
  schedule:
    - cron: "0 0 * * *" # 매일 오전 12시(UTC) 실행

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@khu.ac.kr"
          git remote add upstream https://github.com/iceprins/Algorithm-Study.git

      - name: Fetch and Merge Changes
        run: |
          git fetch upstream main
          git merge upstream/main
          git push origin main

      - name: Verify Changes
        run: |
          git log --oneline origin/main..HEAD

