name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # 매 6시간마다 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Fork
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: false
        clean: true
        persist-credentials: false

    - name: Remove Submodule Configurations
      run: |
        rm -rf .git/modules/*  # 서브모듈 캐시 강제 삭제
        git submodule deinit --all --force || true  # 모든 서브모듈 비활성화
        git config --local --remove-section submodule || true  # 서브모듈 설정 제거
        find . -name ".gitmodules" -delete  # .gitmodules 파일 삭제

    - name: Configure Safe Directory
      run: |
        git config --global --add safe.directory /home/runner/work/Algorithm-Study/Algorithm-Study

    - name: Configure Git User
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Set Upstream
      run: |
        git remote add upstream https://github.com/example/test.git
        git fetch upstream
        git checkout main || git checkout -b main
        git merge --no-edit upstream/main || true

    - name: Push Changes to Fork
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main || true

