name: Synchronize to forked repo

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://github.com/jdoeun/Algorithm-Study.git
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@khu.ac.kr"
      
      - name: Push changes to forked-repo 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push -f forked-repo main
      
      - name: Clean up
        run: |
          git remote remove forked-repo

