name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *" # 매일 00:00 UTC에 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Fork
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 전체 히스토리 가져오기
        submodules: false  # 서브모듈 무시

    - name: Configure Git User
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Set Upstream
      run: |
        git remote add upstream https://github.com/iceprins/Algorithm-Study.git
        git fetch upstream
        git checkout main || git checkout -b main
        git merge upstream/main --no-edit || true

    - name: Push Changes to Fork
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main || true
